# API Keys Configuration
# DO NOT commit this file to version control!
# Add this file to .gitignore

NEWS_API_KEY=8dfa263dbda54585bd3b62034f533f59
GEMINI_API_KEY=AIzaSyARY-mdaaGym8YDVdDHIpelhV48zMo1hNE
